name: Build and release package binaries
on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Hash of the commit to build Smelter from'
        required: true
        type: string
      description:
        description: 'Brief description of tested release'
        type: string
        default: ''
      linux-x86_64:
        description: 'Linux x86_64'
        type: boolean
        default: true
      linux-arm64:
        description: 'Linux arm64'
        type: boolean
        default: false
      macos-x86_64:
        description: 'MacOS x86_64'
        type: boolean
        default: false
      macos-arm64:
        description: 'MacOS arm64'
        type: boolean
        default: true
      docker:
        description: 'Publish docker rc'
        type: boolean
        default: false

jobs:
  binaries-linux-x86_64:
    runs-on: ubuntu-24.04
    if: ${{ inputs.linux-x86_64 }}
    steps:
      - name: 🛠 Install system dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libopus-dev

      - name: Show installed FFmpeg version
        run: ffmpeg -version

      - name: 🔧 Install the rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 📦 Package
        run: cargo run -p tools --bin package_for_release

      - name: Run dependency check
        run: ./tools/build/smelter/dependency_check

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_linux_x86_64.tar.gz
          path: ./tools/build/smelter_linux_x86_64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_with_web_renderer_linux_x86_64.tar.gz
          path: ./tools/build/smelter_with_web_renderer_linux_x86_64.tar.gz

  binaries-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.linux-arm64 }}
    steps:
      - name: 🛠 Install system dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libopus-dev curl git build-essential libssl-dev pkg-config libclang-dev

      - name: Show installed FFmpeg version
        run: ffmpeg -version

      - name: 🔧 Install the rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 📦 Package
        run: cargo run -p tools --bin package_for_release

      - name: Run dependency check
        run: ./tools/build/smelter/dependency_check

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_linux_aarch64.tar.gz
          path: ./tools/build/smelter_linux_aarch64.tar.gz

  binaries-macos-x86_64:
    runs-on: macos-13
    if: ${{ inputs.macos-x86_64 }}
    steps:
      - name: 🛠 Install system dependencies
        run: brew install ffmpeg

      - name: Show installed FFmpeg version
        run: ffmpeg -version

      - name: 🔧 Install the rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 📦 Package
        run: cargo run -p tools --bin package_for_release

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_darwin_x86_64.tar.gz
          path: ./tools/build/smelter_darwin_x86_64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_with_web_renderer_darwin_x86_64.tar.gz
          path: ./tools/build/smelter_with_web_renderer_darwin_x86_64.tar.gz

  binaries-macos-aarch64:
    runs-on: macos-14
    if: ${{ inputs.macos-arm64 }}
    steps:
      - name: 🛠 Install system dependencies
        run: brew install ffmpeg

      - name: Show installed FFmpeg version
        run: ffmpeg -version

      - name: 🔧 Install the rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 📦 Package
        run: cargo run -p tools --bin package_for_release

      - name: Run dependency check
        run: ./tools/build/smelter/dependency_check

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_darwin_aarch64.tar.gz
          path: ./tools/build/smelter_darwin_aarch64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: smelter_with_web_renderer_darwin_aarch64.tar.gz
          path: ./tools/build/smelter_with_web_renderer_darwin_aarch64.tar.gz

  release-rc:
    runs-on: ubuntu-24.04
    needs: [binaries-linux-x86_64, binaries-linux-aarch64, binaries-macos-x86_64, binaries-macos-aarch64]
    if: >-
      ${{ 
        (
          needs.binaries-linux-x86_64.result == 'success' ||
          needs.binaries-linux-aarch64.result == 'success' ||
          needs.binaries-macos-x86_64.result == 'success' ||
          needs.binaries-macos-aarch64.result == 'success'
        ) &&
        always() &&
        !failure() &&
        !cancelled()
      }}
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: Downlad smelter binaries
        uses: actions/download-artifact@v5

      - name: List files
        run: ls -R ${{ github.workspace }}

        # The date's format is 'yyyy-mm-dd hh:mm'
        # E.g. 2025-10-16 12:27
      - name: Create release name
        id: release-name
        run: |
          HASH='${{ inputs.commit_hash }}'
          SHORT_HASH=${HASH:0:8}
          RELEASE_NAME="$(date +'%F %H:%M') $SHORT_HASH"
          echo "SHORT_HASH=$SHORT_HASH" >> "$GITHUB_OUTPUT"
          echo "RELEASE_NAME=$RELEASE_NAME" >> "$GITHUB_OUTPUT"

      - name: Release Smelter RC
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release-name.outputs.RELEASE_NAME }}
          tag_name: ${{ steps.release-name.outputs.SHORT_HASH }}
          body: ${{ inputs.description }}
          files: ${{ github.workspace }}/**/smelter*.tar.gz
          preserve_order: true


  docker-amd64:
    runs-on: ubuntu-latest
    if: ${{ inputs.docker }}
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 🛠️ Setup Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🔨 Build Smelter image
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/smelter-labs/smelter-rc:${{ github.sha }} -f tools/docker/slim.Dockerfile .

      - name: 📤  Upload image
        run: docker push ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}

  docker-arm64:
    needs: [docker-amd64, docker-with-web-renderer-arm64]
    if: ${{ inputs.docker }}
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 🛠️ Setup Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🎣 Pull Smleter AMD64 image
        run: |
          docker pull ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}
          echo "AMD64_IMAGE_ID=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/smelter-labs/smelter-rc:${{ github.sha }})" >> "$GITHUB_ENV"

      - name: 🔨 Build Smelter ARM64 image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/smelter-labs/smelter-rc:${{ github.sha }} -f tools/docker/slim.Dockerfile .

      - name: ⏩ Push ARM64 image
        run: |
          docker push ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}
          echo "ARM64_IMAGE_ID=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/smelter-labs/smelter-rc:${{ github.sha }})" >> "$GITHUB_ENV"

      - name: 🔗 Merge AMD64 and ARM64 images
        run: |
          docker manifest create ghcr.io/smelter-labs/smelter-rc:${{ github.sha }} ${{ env.AMD64_IMAGE_ID }} ${{ env.ARM64_IMAGE_ID }}
          docker manifest annotate ghcr.io/smelter-labs/smelter-rc:${{ github.sha }} ${{ env.AMD64_IMAGE_ID }} --arch amd64
          docker manifest annotate ghcr.io/smelter-labs/smelter-rc:${{ github.sha }} ${{ env.ARM64_IMAGE_ID }} --arch arm64

      - name: 📤  Upload image
        run: docker manifest push ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}

  docker-with-web-renderer-amd64:
    if: ${{ inputs.docker }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 🛠️ Setup Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🔨 Build Smelter with Web Renderer image
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer -f tools/docker/full.Dockerfile .

      - name: 📤  Upload image
        run: docker push ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer

  docker-with-web-renderer-arm64:
    if: ${{ inputs.docker }}
    needs: docker-with-web-renderer-amd64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'software-mansion/smelter'
          ref: '${{ inputs.commit_hash }}'

      - name: 🛠️ Setup Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🎣 Pull Smleter AMD64 image
        run: |
          docker pull ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer
          echo "AMD64_IMAGE_ID=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer)" >> "$GITHUB_ENV"

      - name: 🔨 Build Smelter ARM64 image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer -f tools/docker/full.Dockerfile .

      - name: ⏩ Push ARM64 image
        run: |
          docker push ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer
          echo "ARM64_IMAGE_ID=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer)" >> "$GITHUB_ENV"

      - name: 🔗 Merge AMD64 and ARM64 images
        run: |
          docker manifest create ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer ${{ env.AMD64_IMAGE_ID }} ${{ env.ARM64_IMAGE_ID }}
          docker manifest annotate ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer ${{ env.AMD64_IMAGE_ID }} --arch amd64
          docker manifest annotate ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer ${{ env.ARM64_IMAGE_ID }} --arch arm64

      - name: 📤  Upload image
        run: docker manifest push ghcr.io/smelter-labs/smelter-rc:${{ github.sha }}-web-renderer
